project_name: go-release-example
env:
  - CGO_ENABLED=0
archives:
  - id: go-release-example
    builds:
      - go-release-example
    format: binary
builds:
  - id: go-release-example
    binary: go-release-example
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
universal_binaries:
  - id: go-release-example
    replace: false
