name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.variables.outputs.go_version }}
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          changelog-file: CHANGELOG.md
          update-file: version
          changelog-generator-opt: "emojis=true"
          force-bump-patch-version: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # # - uses: asdf-vm/actions/install@v1
      # - uses: go-semantic-release/action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     update-file: version
      # - run: git fetch --all # Re-pull the repo to get the latest tags
      # - uses: goreleaser/goreleaser-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     args: release --rm-dist
